# Generated by Django 4.0.5 on 2022-06-26 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDeEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=30)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptodo.categoriadeestado')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Fecha', models.DateField()),
                ('Contenido', models.TextField(max_length=8000)),
                ('Completado', models.BooleanField()),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptodo.estado')),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptodo.proyecto')),
            ],
        ),
    ]
