# Generated by Django 4.0.5 on 2022-06-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='CategoriaDeEstado',
        ),
    ]
