# Generated by Django 4.0.5 on 2022-06-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0003_proyecto_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='PorDefecto',
            field=models.BooleanField(default=0),
        ),
    ]
