# Generated by Django 4.0.5 on 2022-07-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0005_remove_tarea_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='Descripcion',
            field=models.TextField(default='', max_length=8000),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='Clave',
            field=models.CharField(max_length=10),
        ),
    ]
