# Generated by Django 4.0.5 on 2022-07-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0006_proyecto_descripcion_alter_proyecto_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='Clave',
        ),
    ]
