# Generated by Django 4.0.5 on 2022-07-25 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0007_remove_proyecto_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='Completado',
        ),
    ]
