# Generated by Django 4.0.5 on 2022-07-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0008_remove_tarea_completado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
    ]
