# Generated by Django 4.0.5 on 2022-07-25 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0009_categoriaestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaestado',
            name='Cosa',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estado',
            name='Categoria',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='apptodo.categoriaestado'),
            preserve_default=False,
        ),
    ]
