# Generated by Django 4.0.5 on 2022-07-25 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0010_categoriaestado_cosa_estado_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaestado',
            name='Cosa',
        ),
    ]
